services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: usuariodocker
      POSTGRES_PASSWORD: dbvotacao

      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-votacao-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
        - api-network
networks:
  api-network:
    driver: bridge

volumes:
  db-votacao-data: