name: Deploy Java project to Azure Function App

on:
  push:
    branches:
      - develop

env:
  AZURE_FUNCTIONAPP_NAME: 'api-votacao'
  GRADLE_PROJECT_DIRECTORY: '.'
  JAVA_VERSION: '11'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Java SDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: 'Run Gradle Build'
      working-directory: ${{ env.GRADLE_PROJECT_DIRECTORY }}
      run: |
        ./gradlew build

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './${{ env.GRADLE_PROJECT_DIRECTORY }}/build/libs'
